# configs/config.yaml
defaults:
  - _self_

project:
  name: mlops-starter

dataset:
  path: ${hydra:runtime.cwd}/data/raw

model:
  name: baseline_model
  params:
    learning_rate: 0.001
    batch_size: 32

logging:
  config: ${hydra:runtime.cwd}/configs/logging.yaml
