name: Docker Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Build Train Image
        run: docker build --target train -t mlops-starter-kit:train .
      - name: Build Serve Image
        run: docker build --target serve -t mlops-starter-kit:serve .
      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker images
        run: |
          docker tag mlops-starter-kit:train ${{ secrets.DOCKERHUB_USERNAME }}/mlops-starter-kit:train-${{ github.sha }}
          docker tag mlops-starter-kit:serve ${{ secrets.DOCKERHUB_USERNAME }}/mlops-starter-kit:serve-${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops-starter-kit:train-${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops-starter-kit:serve-${{ github.sha }}
